# ===== 测试环境配置 =====

server:
  port: "9902"

# WebSocket 配置
ws:
  port: 9903

# 任务配置
task:
  encrypt_key: "ChiuPC_VideoDedup_AES256_CBC_KEY"
  default_concurrent: 2
  max_concurrent: 5

# MySQL 配置
mysql:
  host: 193.218.201.251
  port: 3306
  username: Chiu-PC
  password: TpEMtDHB2Ra7XnXp
  database: chiu-pc

# Redis 配置
redis:
  host: 193.218.201.251
  port: 6379
  password: zl1223473749

# JWT 配置
jwt:
  secret: "Chiu-PC_2026_JWT_Secret_Key_Dev"
  access_expire_min: 15
  refresh_expire_day: 7
  issuer: "Chiu-PC-Server-Dev"

# 日志配置
log:
  log_file_path: ./logs/biz/
  log_file_name: app.log
  max_size: 1
  max_age: 30
  max_backups: 7
  compress: true

# Swagger 文档
apiDoc:
  open: true
