// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {
            "name": "湫创科技",
            "url": "https://qiuya.cc"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/api/auth/login": {
            "post": {
                "tags": ["认证 - AUTH"],
                "summary": "用户登录（账号不存在时自动创建）",
                "description": "使用账号密码登录。如果账号不存在，会自动创建新用户，然后返回双 Token",
                "accept": "application/json",
                "produces": "application/json",
                "parameters": [
                    {
                        "in": "body",
                        "name": "body",
                        "required": true,
                        "schema": {
                            "type": "object",
                            "properties": {
                                "account": { "type": "string", "example": "admin" },
                                "password": { "type": "string", "example": "123456" }
                            },
                            "required": ["account", "password"]
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "登录成功",
                        "schema": {
                            "type": "object",
                            "properties": {
                                "access_token": { "type": "string" },
                                "refresh_token": { "type": "string" },
                                "expires_in": { "type": "integer" },
                                "user": {
                                    "type": "object",
                                    "properties": {
                                        "id": { "type": "integer" },
                                        "account": { "type": "string" },
                                        "nick_name": { "type": "string" },
                                        "avatar": { "type": "string" },
                                        "role": { "type": "integer" }
                                    }
                                }
                            }
                        }
                    },
                    "400": {
                        "description": "请求参数错误",
                        "schema": { "type": "object", "properties": { "error": { "type": "string" } } }
                    },
                    "401": {
                        "description": "密码错误",
                        "schema": { "type": "object", "properties": { "error": { "type": "string" } } }
                    }
                }
            }
        },
        "/api/auth/refresh": {
            "post": {
                "tags": ["认证 - AUTH"],
                "summary": "刷新 Access Token",
                "description": "使用 Refresh Token 获取新的 Access Token",
                "accept": "application/json",
                "produces": "application/json",
                "parameters": [
                    {
                        "in": "body",
                        "name": "body",
                        "required": true,
                        "schema": {
                            "type": "object",
                            "properties": {
                                "refresh_token": { "type": "string", "example": "eyJhbGciOiJIUzI1NiIs..." }
                            },
                            "required": ["refresh_token"]
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "刷新成功",
                        "schema": {
                            "type": "object",
                            "properties": {
                                "access_token": { "type": "string" },
                                "expires_in": { "type": "integer" }
                            }
                        }
                    },
                    "401": {
                        "description": "RefreshToken 无效",
                        "schema": { "type": "object", "properties": { "error": { "type": "string" } } }
                    }
                }
            }
        },
        "/api/auth/check": {
            "post": {
                "tags": ["认证 - AUTH"],
                "summary": "校验登录状态",
                "description": "验证 Access Token 是否有效，并返回用户信息",
                "accept": "application/json",
                "produces": "application/json",
                "parameters": [
                    {
                        "in": "body",
                        "name": "body",
                        "required": true,
                        "schema": {
                            "type": "object",
                            "properties": {
                                "access_token": { "type": "string", "example": "eyJhbGciOiJIUzI1NiIs..." }
                            },
                            "required": ["access_token"]
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "校验结果",
                        "schema": {
                            "type": "object",
                            "properties": {
                                "valid": { "type": "boolean" },
                                "user": {
                                    "type": "object",
                                    "properties": {
                                        "id": { "type": "integer" },
                                        "account": { "type": "string" },
                                        "nick_name": { "type": "string" },
                                        "avatar": { "type": "string" },
                                        "role": { "type": "integer" }
                                    }
                                }
                            }
                        }
                    }
                }
            }
        },
        "/api/health": {
            "get": {
                "tags": ["系统"],
                "summary": "健康检查",
                "description": "服务健康检查接口",
                "produces": "application/json",
                "responses": {
                    "200": {
                        "description": "服务正常",
                        "schema": {
                            "type": "object",
                            "properties": {
                                "status": { "type": "string", "example": "ok" },
                                "service": { "type": "string", "example": "Chiu-PC-Server" }
                            }
                        }
                    }
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:         "1.0",
	Host:            "localhost:9902",
	BasePath:        "/",
	Schemes:         []string{"http", "https"},
	Title:           "Chiu-PC-Server API",
	Description:     "湫创 PC 端认证服务 API 文档",
	SwaggerTemplate: docTemplate,
	LeftDelim:       "{{",
	RightDelim:      "}}",
}

func init() {
	swag.Register(swag.Name, SwaggerInfo)
}
